insert $r isa restaurant,
    has name "Gavin's Bagel Bar",
    has address "62 Downer Ave",
    has phone-number "732-546-4315";

insert $bm isa menu,
    has name "Breakfast";

insert $lm isa menu,
    has name "Lunch";

insert $bec isa food,
    has name "Bacon egg and cheese",
    has description "Breakfast sandwich with bacon egg and cheese served on a bagel",
    has price 5.50;

insert $sec isa food,
    has name "Sausage egg and cheese",
    has description "Breakfast sandwich with bacon egg and cheese served on a bagel",
    has price 5.50;

insert $dia isa food,
    has name "Hastag",
    has description "The ultimate breakfast sandwich with sausage egg and cheese on a bagel, topped with a hashbrown and sriracha",
    has price 7.50;

insert $tclub isa food,
    has name "Turkey club",
    has description "Turkey sandwich with bacon lettuce and tomato, cheese optional",
    has price 8.00;

insert $ib isa ingredient,
    has name "bacon",
    has spice-level "none";

insert $ie isa ingredient,
    has name "egg",
    has spice-level "none";

insert $ic isa ingredient,
    has name "cheese",
    has spice-level "none";
    
insert $is isa ingredient,
    has name "sausage",
    has spice-level "none";

insert $ibagel isa ingredient,
    has name "bagel",
    has spice-level "none";

insert $ibagel isa ingredient,
    has name "hashbrown",
    has spice-level "none";

insert $ibagel isa ingredient,
    has name "avocado",
    has spice-level "none";

insert $ibagel isa ingredient,
    has name "turkey",
    has spice-level "none";


insert $isri isa ingredient,
    has name "sriracha",
    has spice-level "medium";


#####################
##  RELATIONSHIPS  ##
#####################

##  MENUS  ##
match
  $bmenu isa menu, has name "Breakfast";
  $res isa restaurant, has name "Gavin's Bagel Bar";
insert $gbb-bmenu (restaurant-with-menu: $res, menu-for-restaurant: $bmenu) isa restaurant-menu;

match
  $lmenu isa menu, has name "Lunch";
  $res isa restaurant, has name "Gavin's Bagel Bar";
insert $gbb-lmenu (restaurant-with-menu: $res, menu-for-restaurant: $lmenu) isa restaurant-menu;

## MENU ITEMS ##
match
    $menu isa menu, has name "Breakfast";
    $bec isa food, has name "Bacon egg and cheese";
insert $bec-menu (menu-with-items: $menu, item-on-menu: $bec) isa menu-item;

match
    $menu isa menu, has name "Breakfast";
    $bec isa food, has name "Sausage egg and cheese";
insert $bec-menu (menu-with-items: $menu, item-on-menu: $bec) isa menu-item;

match
    $menu isa menu, has name "Breakfast";
    $bec isa food, has name "Hashtag";
insert $bec-menu (menu-with-items: $menu, item-on-menu: $bec) isa menu-item;

match
    $menu isa menu, has name "Lunch";
    $bec isa food, has name "Turkey club";
insert $bec-menu (menu-with-items: $menu, item-on-menu: $bec) isa menu-item;

## FOOD INGREDIENTS ##
match
    $bec isa food, has name "Bacon egg and cheese";
    $ing isa ingredient, has name "bacon";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Bacon egg and cheese";
    $ing isa ingredient, has name "egg";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Bacon egg and cheese";
    $ing isa ingredient, has name "cheese";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Bacon egg and cheese";
    $ing isa ingredient, has name "bagel";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Sausage egg and cheese";
    $ing isa ingredient, has name "bagel";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Sausage egg and cheese";
    $ing isa ingredient, has name "sausage";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Sausage egg and cheese";
    $ing isa ingredient, has name "egg";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Sausage egg and cheese";
    $ing isa ingredient, has name "cheese";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Hashtag";
    $ing isa ingredient, has name "sausage";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Hashtag";
    $ing isa ingredient, has name "egg";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Hashtag";
    $ing isa ingredient, has name "cheese";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Hashtag";
    $ing isa ingredient, has name "bagel";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Hashtag";
    $ing isa ingredient, has name "sriracha";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Hashtag";
    $ing isa ingredient, has name "hasbrown";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Turkey club";
    $ing isa ingredient, has name "bagel";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Turkey club";
    $ing isa ingredient, has name "turkey";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Turkey club";
    $ing isa ingredient, has name "bacon";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

match
    $bec isa food, has name "Turkey club";
    $ing isa ingredient, has name "bagel";
insert $bec-ing (menu-item-made: $bec, made-with-ingredient: $ing) isa made-with;

## TOPPINGS ##
match 
    $food isa food, has name "Turkey club";
    $top isa ingredient, has name "avocado";
insert $food-top (menu-item-made: $food, topping-ingredient: $top) isa topping;
    $food-top has additional-cost 1.00;

match 
    $food isa food, has name "Turkey club";
    $top isa ingredient, has name "cheese";
insert $food-top (menu-item-made: $food, topping-ingredient: $top) isa topping;
    $food-top has additional-cost 0.50;